name: hybrid_storage_app
description: "Application mobile pour la solution de stockage hybride smartphone-ordinateur."
# Empêcher la publication accidentelle sur pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dépendances de l'application.
# Elles sont choisies en fonction des spécifications techniques et UX/UI.
dependencies:
  flutter:
    sdk: flutter

  # Pour la gestion d'état, selon le pattern BLoC.
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Pour l'injection de dépendances, afin de garder une architecture propre.
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Pour les communications réseau.
  # gRPC pour les transferts de fichiers lourds.
  grpc: ^3.2.4
  # WebSockets pour la communication temps-réel.
  web_socket_channel: ^2.4.0
  # Découverte réseau via mDNS.
  multicast_dns: ^0.3.2+3
  # Vérification de la connectivité.
  connectivity_plus: ^5.0.2

  # Pour la persistance des données.
  # Base de données locale SQLite.
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  # Stockage sécurisé pour les clés cryptographiques.
  flutter_secure_storage: ^9.0.0

  # Pour l'interface utilisateur et les fonctionnalités UX.
  # Scan de QR Code pour l'appairage.
  qr_code_scanner: ^1.0.1
  # Icônes Cupertino pour la cohérence sur iOS.
  cupertino_icons: ^1.0.6
  # Pour la mise en forme (dates, nombres).
  intl: ^0.18.1
  # Pour afficher des messages temporaires (Toast/Snackbar).
  fluttertoast: ^8.2.4
  # Pour la gestion des permissions.
  permission_handler: ^11.1.0
  # Pour générer des identifiants uniques pour les transferts.
  uuid: ^4.3.3
  # Pour les polices Google, si le design system est étendu.
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Outils pour la génération de code (notamment pour l'injection de dépendances).
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Pour ajouter des assets comme des images ou des polices.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
